package secondbrain.domain.tools;

/**
 * Common argument names used across various tools. By using these arguments consistently,
 * the meta tools can pass parameters seamlessly between different tools.
 */
public class CommonArguments {
    /**
     * The entity name. This is used to embed the entity name in the sentences that are converted
     * to embeddings to more closely associate the embeddings with the context of the entity.
     */
    public static final String ENTITY_NAME_CONTEXT_ARG = "entityName";
    /**
     * This is the question used to determine the content rating of a document.
     */
    public static final String CONTENT_RATING_QUESTION_ARG = "contentRatingQuestion";
    /**
     * This is the minimum rating a document must have to be included in the context.
     */
    public static final String CONTEXT_FILTER_MINIMUM_RATING_ARG = "contextFilterMinimumRating";
    /**
     * The default rating to assign to documents when no rating can be determined.
     */
    public static final String DEFAULT_RATING_ARG = "defaultRating";
    /**
     * This can be set to true to filter out any documents with a rating greater than the
     * specified minimum rating. It essentially inverts the filtering logic.
     */
    public static final String FILTER_GREATER_THAN_ARG = "filterGreaterThan";
    /**
     * The keywords to use for context filtering.
     */
    public static final String KEYWORDS_ARG = "keywords";
    /**
     * The window size to use when extracting keywords from documents.
     */
    public static final String KEYWORD_WINDOW_ARG = "keywordWindow";
    /**
     * The names of classes implementing the PreProcessingHook interface to apply before initialization.
     * These can be used to generate context before any external data is collected.
     */
    public static final String PREINITIALIZATION_HOOKS_ARG = "preInitializationHooks";
    /**
     * The names of classes implementing the PreProcessingHook interface to apply before processing the document.
     * These are used to manipulate the context returned from external sources and generated by the pre-initialization hooks.
     */
    public static final String PREPROCESSOR_HOOKS_ARG = "preProcessorHooks";
    /**
     * The name of classes implementing the PostInferenceHook interface to apply after passing the
     * context to the LLM.
     */
    public static final String POSTINFERENCE_HOOKS_ARG = "postInferenceHooks";
    /**
     * Whether to summarize the document before including it in the final context.
     */
    public static final String SUMMARIZE_DOCUMENT_ARG = "summarizeDocument";
    /**
     * The prompt to use when summarizing the document.
     */
    public static final String SUMMARIZE_DOCUMENT_PROMPT_ARG = "summarizeDocumentPrompt";
    /**
     * The number of days to look back when retrieving recent documents.
     */
    public static final String DAYS_ARG = "days";
}
