# action.yml
name: 'SecondBrainAction'
description: 'AI powered git commit message generator with Ollama'
branding:
  icon: 'box'
  color: 'green'
inputs:
  tool:
    description: 'The tool to use'
    required: true
    default: 'GitHubDiffs'
  prompt:
    description: 'The LLM prompt'
    required: true
    default: 'Provide a summary of the changes from the git diffs. Use plain language. You will be penalized for offering code suggestions. You will be penalized for sounding excited about the changes.'
  token:
    description: 'GitHub access token'
    required: false
  owner:
    description: 'GitHub repo owner'
    required: false
    default: ${{ github.repository_owner }}
  repo:
    description: 'GitHub repo'
    required: false
    default: ${{ github.event.repository.name }}
  githubDays:
    description: 'GitHub days'
    required: false
    default: "1"
  sha:
    description: 'Git commit SHA'
    required: false
  summarizeIndividualDiffs:
    description: 'Whether to summarize individual diffs'
    required: false
    default: 'true'
  gitDiffModel:
    description: 'The model used to create git diffs'
    required: false
    default: 'qwen3:30b-a3b'
  model:
    description: 'The model used to answer the prompt'
    required: true
    default: 'llama3.2:3b'
  zenDeskToken:
    description: 'The ZenDesk Access Token'
    required: false
    default: ''
  zenDeskUser:
    description: 'The ZenDesk User'
    required: false
    default: ''
  zenDeskUrl:
    description: 'The ZenDesk URL'
    required: false
    default: ''
  zenDeskDays:
    description: 'The number of days worth of tickets to summarize'
    required: false
    default: '30'
  zenStartPeriod:
    description: 'The start period for ZenDesk tickets in the ISO date-time format e.g. 2011-12-03T10:15:30+01:00. Leave blank to default to the last 31 days.'
    required: false
    default: ''
  zenEndPeriod:
    description: 'The end period for ZenDesk tickets in the ISO date-time format e.g. 2011-12-03T10:15:30+01:00. Leave blank to default to the last 31 days.'
    required: false
    default: ''
  zenDeskOrganization:
    description: 'The organization to summarize'
    required: false
    default: ''
  contextFilterQuestion:
    description: 'An optional question to filter the context of the ZenDesk tickets'
    required: false
    default: ''
  contextFilterMinimumRating:
    description: 'The minimum rating to filter the context of the ZenDesk tickets'
    required: false
    default: ''
  zendeskRecipient:
    description: 'The recipient for the ZenDesk ticket'
    required: false
    default: ''
  ticketSummaryPrompt:
    description: 'The custom prompt to use for summarizing ZenDesk tickets'
    required: false
    default: ''
  zendeskSaveIndividual:
    description: 'Set to true to save the result of each individual ZenDesk ticket summary to a file.'
    required: false
    default: ''
  contextWindow:
    description: 'The size of the context window'
    required: false
    default: '8192'
  diffContextWindow:
    description: 'The size of the diff context window'
    required: false
    default: '8192'
  slackChannel:
    description: 'The slack channel to summarize'
    required: false
    default: ''
  slackDays:
    description: 'The number of days worth of Slack messages to consume'
    required: false
    default: '7'
  slackAccessToken:
    description: 'The Slack access token'
    required: false
    default: ''
  slackExcludedOrgs:
    description: 'Organizations to exclude from the Slack summary'
    required: false
    default: ''
  outputFormat:
    description: 'The output format. Set markdn for Slack markdown, or leave blank for regular markdown.'
    required: false
    default: ''
  directoryScanKeywords:
    description: 'Keywords to scan for in the source content.'
    required: false
    default: ''
  directoryScanPathSpec:
    description: 'An Ant pathspec used to select files during a directory scan.'
    required: false
    default: ''
  directoryScanDirectory:
    description: 'The directory to scan.'
    required: false
    default: ''
  fileContextWindow:
    description: 'The context window used when summarising the content from an individual file.'
    required: false
    default: '8192'
outputs:
  response:
    description: 'The LLM response'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mcasperson/secondbrainaction:latest'
  args:
    - ${{ inputs.prompt }}
    - ${{ inputs.outputFormat }}
  env:
    SB_TOOLS_FORCE: "${{ inputs.tool }}"
    SB_OLLAMA_GITDIFFMODEL: "${{ inputs.gitDiffModel }}"
    SB_OLLAMA_MODEL: "${{ inputs.model }}"
    SB_OLLAMA_SUMMARIZEINDIVIDUALDIFFS: "${{ inputs.summarizeIndividualDiffs }}"
    SB_GITHUB_ACCESSTOKEN: "${{ inputs.token }}"
    SB_GITHUB_OWNER: "${{ inputs.owner }}"
    SB_GITHUB_REPO: "${{ inputs.repo }}"
    SB_GITHUB_SHA: "${{ inputs.sha }}"
    SB_GITHUB_DAYS: "${{ inputs.githubDays }}"
    SB_ZENDESK_ACCESSTOKEN: "${{ inputs.zenDeskToken }}"
    SB_ZENDESK_USER: "${{ inputs.zenDeskUser }}"
    SB_ZENDESK_URL: "${{ inputs.zenDeskUrl }}"
    SB_ZENDESK_DAYS: "${{ inputs.zenDeskDays }}"
    SB_ZENDESK_STARTPERIOD: "${{ inputs.zenStartPeriod }}"
    SB_ZENDESK_ENDPERIOD: "${{ inputs.zenEndPeriod }}"
    SB_ZENDESK_NUMCOMMENTS: 10
    SB_ZENDESK_ORGANIZATION: "${{ inputs.zenDeskOrganization }}"
    SB_ZENDESK_CONTEXTFILTERQUESTION: ${{ inputs.contextFilterQuestion }}
    SB_ZENDESK_CONTEXTFILTERMINIMUMRATING: ${{ inputs.contextFilterMinimumRating }}
    SB_ZENDESK_RECIPIENT: "${{ inputs.zendeskRecipient }}"
    SB_ZENDESK_SAVEINDIVIDUAL: "${{ inputs.zendeskSaveIndividual }}"
    SB_OLLAMA_CONTEXTWINDOW: "${{ inputs.contextWindow }}"
    SB_OLLAMA_DIFFCONTEXTWINDOW: "${{ inputs.diffContextWindow }}"
    # This reduces the number of API calls we need to make to the ZenDesk API.
    SB_ZENDESK_FILTERBYORGANIZATION: "true"
    SB_ZENDESK_TICKETSUMMARYPROMPT: "${{ inputs.ticketSummaryPrompt }}"
    SB_SLACK_CHANNEL: "${{ inputs.slackChannel }}"
    SB_SLACK_DAYS: "${{ inputs.slackDays }}"
    SB_SLACK_ACCESSTOKEN: "${{ inputs.slackAccessToken }}"
    SB_SLACK_EXCLUDEDORGS: "${{ inputs.slackExcludedOrgs }}"
    SB_DIRECTORYSCAN_PATHSPEC: "${{ inputs.directoryScanPathSpec }}"
    SB_DIRECTORYSCAN_KEYWORDS: "${{ inputs.directoryScankeywords }}"
    SB_OLLAMA_FILEWINDOW: "${{ inputs.fileContextWindow }}"
    SB_DIRECTORYSCAN_DIRECTORY: "${{ inputs.directoryScanDirectory }}"


