# action.yml
name: 'SecondBrainAction'
description: 'AI powered git commit message generator with Ollama'
branding:
  icon: 'box'
  color: 'green'
inputs:
  tool:
    description: 'The tool to use'
    required: true
    default: 'GitHubDiffs'
  prompt:
    description: 'The LLM prompt'
    required: true
    default: 'Provide a summary of the changes from the git diffs. Use plain language. You will be penalized for offering code suggestions. You will be penalized for sounding excited about the changes.'
  token:
    description: 'GitHub access token'
    required: false
  owner:
    description: 'GitHub repo owner'
    required: false
    default: ${{ github.repository_owner }}
  repo:
    description: 'GitHub repo'
    required: false
    default: ${{ github.event.repository.name }}
  sha:
    description: 'Git commit SHA'
    required: false
  summarizeIndividualDiffs:
    description: 'Whether to summarize individual diffs'
    required: false
    default: 'true'
  gitDiffModel:
    description: 'The model used to create git diffs'
    required: false
    default: 'qwen3:30b-a3b'
  model:
    description: 'The model used to answer the prompt'
    required: true
    default: 'llama3.2:3b'
  zenDeskToken:
    description: 'The ZenDesk Access Token'
    required: false
    default: ''
  zenDeskUser:
    description: 'The ZenDesk User'
    required: false
    default: ''
  zenDeskUrl:
    description: 'The ZenDesk URL'
    required: false
    default: ''
  zenDeskDays:
    description: 'The number of days worth of tickets to summarize'
    required: false
    default: '30'
  zenDeskOrganization:
    description: 'The organization to summarize'
    required: false
    default: ''
  contextWindow:
    description: 'The size of the context window'
    required: false
    default: '8192'
  diffContextWindow:
    description: 'The size of the diff context window'
    required: false
    default: '8192'
  slackChannel:
    description: 'The slack channel to summarize'
    required: false
    default: ''
  slackDays:
    description: 'The number of days worth of Slack messages to consume'
    required: false
    default: '7'
outputs:
  response:
    description: 'The LLM response'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mcasperson/secondbrainaction:latest'
  args:
    - ${{ inputs.prompt }}
  env:
    SB_TOOLS_FORCE: "${{ inputs.tool }}"
    SB_OLLAMA_GITDIFFMODEL: "${{ inputs.gitDiffModel }}"
    SB_OLLAMA_MODEL: "${{ inputs.model }}"
    SB_OLLAMA_SUMMARIZEINDIVIDUALDIFFS: "${{ inputs.summarizeIndividualDiffs }}"
    SB_GITHUB_ACCESSTOKEN: "${{ inputs.token }}"
    SB_GITHUB_OWNER: "${{ inputs.owner }}"
    SB_GITHUB_REPO: "${{ inputs.repo }}"
    SB_GITHUB_SHA: "${{ inputs.sha }}"
    SB_ZENDESK_ACCESSTOKEN: "${{ inputs.zenDeskToken }}"
    SB_ZENDESK_USER: "${{ inputs.zenDeskUser }}"
    SB_ZENDESK_URL: "${{ inputs.zenDeskUrl }}"
    SB_ZENDESK_DAYS: "${{ inputs.zenDeskDays }}"
    SB_ZENDESK_NUMCOMMENTS: 10
    SB_ZENDESK_ORGANIZATION: "${{ inputs.zenDeskOrganization }}"
    SB_OLLAMA_CONTEXTWINDOW: "${{ inputs.contextWindow }}"
    SB_OLLAMA_DIFFCONTEXTWINDOW: "${{ inputs.diffContextWindow }}"
    # This reduces the number of API calls we need to make to the ZenDesk API.
    SB_ZENDESK_FILTERBYORGANIZATION: "true"
    SB_SLACK_CHANNEL: "${{ inputs.slackChannel }}"
    SB_SLACK_DAYS: "${{ inputs.slackDays }}"
