version: '3.8'

services:
  secondbrain:
    image: ghcr.io/mcasperson/secondbrain
    ports:
      - "8080:8080"
      - "8181:8181"
    environment:
      SB_SLACK_CLIENTID: 1234567890.1234567890
      SB_SLACK_CLIENTSECRET: 123456789
      SB_ENCRYPTION_PASSWORD: 123456789
      SB_OLLAMA_URL: http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"