package secondbrain.domain.tools.helloworld;

import com.google.common.collect.ImmutableList;
import io.vavr.control.Try;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import secondbrain.domain.args.ArgsAccessor;
import secondbrain.domain.context.RagDocumentContext;
import secondbrain.domain.context.RagMultiDocumentContext;
import secondbrain.domain.exceptionhandling.ExceptionMapping;
import secondbrain.domain.objects.ToStringGenerator;
import secondbrain.domain.tooldefs.Tool;
import secondbrain.domain.tooldefs.ToolArgs;
import secondbrain.domain.tooldefs.ToolArguments;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A tool that returns a greeting message.
 */
@ApplicationScoped
public class HelloWorld implements Tool<Void> {
    public static final String MESSAGE_ARG = "message";

    @Inject
    private ExceptionMapping exceptionMapping;

    @Inject
    private HelloWorldConfig config;

    @Override
    public String getName() {
        return HelloWorld.class.getSimpleName();
    }

    @Override
    public String getDescription() {
        return "Returns a greeting message";
    }

    @Override
    public List<ToolArguments> getArguments() {
        return ImmutableList.of(new ToolArguments(
                MESSAGE_ARG,
                "The greeting to display",
                "World"));
    }

    @Override
    public List<RagDocumentContext<Void>> getContext(
            final Map<String, String> environmentSettings,
            final String prompt,
            final List<ToolArgs> arguments) {
        return List.of();
    }

    @Override
    public RagMultiDocumentContext<Void> call(
            final Map<String, String> environmentSettings,
            final String prompt,
            final List<ToolArgs> arguments) {

        final HelloWorldConfig.LocalArguments parsedArgs = config.new LocalArguments(arguments, prompt, environmentSettings);

        final Try<RagMultiDocumentContext<Void>> result = Try.of(() -> new RagMultiDocumentContext<Void>(prompt).updateResponse("Hello, " + parsedArgs.getMessage() + "!"));

        return exceptionMapping.map(result).get();
    }

    @Override
    public String getContextLabel() {
        return "Unused";
    }
}

@ApplicationScoped
class HelloWorldConfig {
    /**
     * Utility to access arguments from various sources.
     */
    @Inject
    private ArgsAccessor argsAccessor;

    /**
     * Utility to generate toString() representations of objects.
     */
    @Inject
    private ToStringGenerator toStringGenerator;

    /**
     * We use microprofile config to inject configuration values. These values can
     * be defined in properties files, environment variables, or command line arguments.
     */
    @Inject
    @ConfigProperty(name = "sb.helloworld.message")
    private Optional<String> configMessage;

    /**
     * Getters have to be used to access injected values because the
     * instance of HelloWorldConfig used to create LocalArguments may be
     * a proxy with null fields. The methods, however, will be properly
     * routed to the underlying instance.
     */
    public Optional<String> getConfigMessage() {
        return configMessage;
    }

    public ArgsAccessor getArgsAccessor() {
        return argsAccessor;
    }

    public ToStringGenerator getToStringGenerator() {
        return toStringGenerator;
    }

    /**
     * This class is the combination of runtime config (these can be arguments generated by the LLM and system config)
     * and static config (from application properties).
     */
    public class LocalArguments {
        private final List<ToolArgs> arguments;

        private final String prompt;

        private final Map<String, String> context;

        public LocalArguments(final List<ToolArgs> arguments, final String prompt, final Map<String, String> context) {
            this.arguments = arguments;
            this.prompt = prompt;
            this.context = context;
        }

        public String toString() {
            return getToStringGenerator().generateGetterConfig(this);
        }

        /**
         * This is where we finally get the configuration values. The ArgsAccessor
         * utility checks the various sources of configuration in the correct order.
         */
        public String getMessage() {
            return getArgsAccessor().getArgument(
                    getConfigMessage()::get,
                    arguments,
                    context,
                    HelloWorld.MESSAGE_ARG,
                    HelloWorld.MESSAGE_ARG,
                    "World").value();
        }
    }
}


