name: Build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release/*'
    paths-ignore:
      - 'action.yml'
      - '.github/workflows/*'

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - run: echo "Setting up the environment"

    #      - name: Free Disk Space (Ubuntu)
    #        uses: jlumbroso/free-disk-space@main
    #        with:
    #          # Leave this to "false" to leave common tools
    #          tool-cache: false
    #          dotnet: false
    #
    #          # None of these are required
    #          android: true
    #          haskell: true
    #          large-packages: true
    #          docker-images: true
    #          swap-storage: true

    #      - name: Cache Ollama models
    #        uses: actions/cache@v4
    #        with:
    #          path: ~/.secondbrain
    #          key: secondbrain-${{ runner.os }}

    #      - name: Setup dotnet
    #        uses: actions/setup-dotnet@v4
    #        with:
    #          dotnet-version: 9.0.x

    #      - name: Set up JDK 21
    #        uses: actions/setup-java@v4
    #        with:
    #          distribution: 'temurin'
    #          java-version: '21'
    #          cache: 'maven'

  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

  version:
    runs-on: self-hosted
    needs: checkout

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.1
        with:
          versionSpec: '5.x'

      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v3.1.1
        with:
          overrideConfig: mode=Mainline

  build:
    runs-on: self-hosted
    needs: checkout # rely on checkout to get the code

    steps:
      - name: Build with Maven
        run: mvn --batch-mode clean install

  publish:
    needs: [ build, version ] # rely on build to run tests and version to determine the version
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      - name: Publish to GitHub Packages
        run: mvn --batch-mode -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: create_release
        name: Create Release
        if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'schedule' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.determine_version.outputs.semVer }}+run${{ github.run_number }}-attempt${{ github.run_attempt }}
          draft: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
          name: Release ${{ steps.determine_version.outputs.semVer }} Run ${{ github.run_number }} Attempt ${{ github.run_attempt }}

  docker:
    needs: [ setup, build ] # rely on build to run tests and setup to clean up disk space
    runs-on: self-hosted
    permissions:
      contents: write
      packages: write

    steps:
      # Need some workarounds to support buildkit cache:
      # https://github.com/reproducible-containers/buildkit-cache-dance
      #      - name: Cache
      #        uses: actions/cache@v4
      #        id: cache
      #        with:
      #          path: root-m2
      #          key: cache
      #
      #      - name: inject cache into docker
      #        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
      #        with:
      #          cache-map: |
      #            {
      #              "root-m2": "/root/.m2"
      #            }
      #          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: DockerfileSecondBrain
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/secondbrain:latest
          # https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/secondbrain:latest
          cache-to: type=inline

      # the image appears to be too big to process here
      #      - name: Build and push Docker image for action
      #        uses: docker/build-push-action@v6
      #        with:
      #          file: Dockerfile
      #          context: .
      #          push: true
      #          tags: ghcr.io/${{ github.repository_owner }}/secondbrainaction:latest
      #          cache-from: type=gha
      #          cache-to: type=gha,mode=max

#      - name: Allow ollama models to be cached
#        run: sudo chmod -R 777 ~/.secondbrain