name: Summarize the commit

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#      - 'release/*'

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: SecondBrainAction
        id: secondbrain
        uses: mcasperson/SecondBrain@main
        with:
          prompt: 'Identity any code that might generate an exception or introduce a security vulnerability. Offer suggestions to improve the code.'
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          sha: ${{ github.sha }}
          summarizeIndividualDiffs: 'false'
          model: 'qwen2.5-coder'
      - name: Get the diff summary
        env:
          RESPONSE: ${{ steps.secondbrain.outputs.response }}
        run: echo "$RESPONSE" >> "$GITHUB_STEP_SUMMARY"